import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f7f7fb",
  },
  scroll: {
    padding: 20,
    gap: 14,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  helper: {
    color: "#6b7280",
  },
  hero: {
    backgroundColor: "#111827",
    borderRadius: 22,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitles: {
    flex: 1,
    gap: 4,
  },
  heroTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "800",
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 13,
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#eef1f6",
    padding: 14,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 14,
    elevation: 2,
  },
  statLabel: {
    color: "#6b7280",
    fontSize: 12,
  },
  statValue: {
    color: "#0f172a",
    fontWeight: "700",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: "#eef1f6",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 3,
    gap: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  sectionText: {
    color: "#4b5563",
    fontSize: 14,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#f8fafc",
  },
  chipText: {
    color: "#0f172a",
    fontWeight: "600",
    fontSize: 12,
  },
  photoPlaceholder: {
    alignItems: "center",
    gap: 6,
    paddingVertical: 12,
  },
  projectRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderRadius: 12,
    paddingHorizontal: 10,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#eef2ff",
    marginBottom: 10,
  },
  projectInfo: {
    flex: 1,
    marginRight: 10,
    gap: 2,
  },
  projectName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  projectMeta: {
    fontSize: 12,
    color: "#6b7280",
  },
  projectBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  badgeGreen: {
    backgroundColor: "#ecfdf3",
    borderColor: "#16a34a",
  },
  badgeYellow: {
    backgroundColor: "#fff7ed",
    borderColor: "#f59e0b",
  },
  badgeRed: {
    backgroundColor: "#fef2f2",
    borderColor: "#ef4444",
  },
  badgeBlue: {
    backgroundColor: "#eef2ff",
    borderColor: "#c7d2fe",
  },
  badgeText: {
    fontSize: 11,
    color: "#0f172a",
    fontWeight: "700",
  },
  placeholderText: {
    color: "#0f172a",
    fontWeight: "700",
  },
  placeholderSub: {
    color: "#6b7280",
    fontSize: 12,
    textAlign: "center",
  },
  locationHint: {
    fontSize: 12,
    color: "#6b7280",
  },
  addPhotoButton: {
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  addPhotoButtonDisabled: {
    opacity: 0.5,
  },
  addPhotoText: {
    color: "#0f172a",
    fontWeight: "700",
    fontSize: 13,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 6,
  },
  photoItem: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#f8fafc",
  },
  photo: {
    width: "100%",
    height: "80%",
  },
  photoDate: {
    color: "#4b5563",
    fontSize: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  photoFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    backgroundColor: "#f8fafc",
    borderColor: "#e5e7eb",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0f172a",
  },
  statusPending: {
    backgroundColor: "rgba(249, 115, 22, 0.08)",
    borderColor: "#f97316",
  },
  statusPendingText: {
    color: "#9a3412",
  },
  statusSynced: {
    backgroundColor: "rgba(34, 197, 94, 0.08)",
    borderColor: "#22c55e",
  },
  statusSyncedText: {
    color: "#15803d",
  },
  statusLocal: {
    backgroundColor: "rgba(14, 165, 233, 0.08)",
    borderColor: "#0ea5e9",
  },
  statusLocalText: {
    color: "#0284c7",
  },
  statusError: {
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    borderColor: "#ef4444",
  },
  statusErrorText: {
    color: "#b91c1c",
  },
  syncBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  syncBadgeText: {
    color: "#0f172a",
    fontWeight: "700",
    fontSize: 12,
  },
  syncDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  syncDotPending: {
    backgroundColor: "#f97316",
  },
  syncDotSynced: {
    backgroundColor: "#16a34a",
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#eef2ff",
    borderWidth: 1,
    borderColor: "#e0e7ff",
  },
  seeAllText: {
    color: "#0f172a",
    fontWeight: "700",
    fontSize: 12,
  },
  sectionActions: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  photoPlaceholderThumb: {
    flex: 1,
    height: "80%",
    backgroundColor: "#eef1f6",
    alignItems: "center",
    justifyContent: "center",
  },
  forceSyncButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#ecfeff",
    borderWidth: 1,
    borderColor: "#bae6fd",
  },
  forceSyncText: {
    color: "#0f172a",
    fontWeight: "700",
    fontSize: 12,
  },
  saveButton: {
    marginTop: 6,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#0f172a",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  saveButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
  },
  modalLabel: {
    fontWeight: "700",
    color: "#0f172a",
  },
  modalInput: {
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#f8fafc",
    color: "#0f172a",
    textAlignVertical: "top",
  },
  modalHint: {
    fontSize: 12,
    color: "#6b7280",
  },
  modalActions: {
    flexDirection: "column",
    gap: 8,
  },
  modalButton: {
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  modalPrimary: {
    backgroundColor: "#eef2ff",
    borderColor: "#e0e7ff",
  },
  modalPrimaryText: {
    color: "#0f172a",
    fontWeight: "700",
  },
  modalSecondary: {
    backgroundColor: "#f8fafc",
    borderColor: "#e5e7eb",
  },
  modalSecondaryText: {
    color: "#374151",
    fontWeight: "700",
  },
  rowBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    backgroundColor: "#f8fafc",
    borderColor: "#e5e7eb",
  },
  rowBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0f172a",
  },
});
